---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: PAGES
- type: directory
  path: comunikDashboard
  label: comunikDashboard
  create: all
  match: "**/*"
- type: directory
  path: comunikTelecom
  label: comunikTelecom
  create: all
  match: "**/*"
- type: directory
  path: comunikContact
  label: comunikContact
  create: all
  match: "**/*"
- type: directory
  path: comunikSales
  label: comunikSales
  create: all
  match: "**/*"
- type: directory
  path: comunikVoip
  label: comunikVoip
  create: all
  match: "**/*"
- type: directory
  path: comunikCRM
  label: comunikCRM
  create: all
  match: "**/*"
- type: heading
  label: Home
- type: document
  path: README.md
  label: Homepage
- type: heading
  label: DATA
- type: document
  path: config.json
  label: Site Config
upload_dir: ".vuepress/public"
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run site:develop
